spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          #true : active the default route that work by fetching the registred services in eureka registry server
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  data:
    #we should run redis container first : docker run -p 6379:6379 --name eazyredis -d redis
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG



resilience4j:
  circuitbreaker:
    configs:
      #if we have multiple configuration of circuitBreaker we should instead ( default ) put the name like our: accountsCircuitBreaker
      default:
        #For every 10 calls it will calculate the failure rate. if 50% failures move to the open state.
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        # mean 50% that is depend_on the first properties
        failure-rate-threshold: 50
        #it will wait for 10s and after that move to half-open state
        wait-duration-in-open-state: 10000
