spring:
  application:
    # we should have the same in the git repo for exmp: eurekaServer.yml
    name: eurekaServer
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

# Eureka Dashboard : http://localhost:8070/
# Eureka All instances info :  http://localhost:8070/eureka/apps
# information about cards instances : http://localhost:8070/eureka/apps/cards