services:

  network-deploy-service:
    networks:
      - eazybank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.33.5.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      serverconfig:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://serverconfig:8071/"
      SPRING_PROFILES_ACTIVE: qa

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      servereureka:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servereureka:8070/eureka/