services:

  network-deploy-service:
    networks:
      - eazybank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      serverconfig:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://serverconfig:8071/"
      SPRING_PROFILES_ACTIVE: qa

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      servereureka:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servereureka:8070/eureka/